#!/usr/bin/python
import requests
import os
import sys
from sh import tail
if (len(sys.argv) < 4):
   print("Please pass the Graylog server address as the first parameter and the port as the second parameter")
   sys.exit(1)
if (sys.argv[1] == ""):
   print("Please pass the Graylog server address as the first parameter")
   sys.exit(1)
if (sys.argv[2] == ""):
   print("Please pass the Graylog server port as the second parameter")
   sys.exit(1)
if (sys.argv[3] == ""):
   print("Please pass the message to send as the third parameter")
   sys.exit(1)
osdet=os.uname()
data = '{"message":"' + sys.argv[3] + '", "host": "' + osdet[1] + '"}'
host = "http://" + sys.argv[1] + ":" + sys.argv[2] + "/gelf"
r = requests.post(host, data=data)
  
